print warnings in release script if xml-linting fails The build was successful, so it doesn't seem to be a problem per-se, but it is a good idea to correct these errors non-the-less.

diff --git a/prepare-release b/prepare-release
--- a/prepare-release
+++ b/prepare-release
@@ -46,6 +46,11 @@ elif [ "$1" = 'post-build' ]; then
 	else
 		echo >&2 'REMEMBER: Change to a valid distribution before release'
 	fi
+	if ! xmllint --nonet --valid --noout $(find doc/ -maxdepth 1 -name '*.xml'); then
+		echo >&2 'WARNING: original docbook manpages have errors!'
+	elif ! xmllint --nonet --valid --noout $(find doc/ -mindepth 2 -maxdepth 2 -name '*.xml'); then
+		echo >&2 'WARNING: translated docbook manpages have errors, but originals are okay!'
+	fi
 elif [ "$1" = 'library' ]; then
 	librarysymbols() {
 		echo "Checking $1 in version $2"
