move hash test to libapt-testcases and add a few more tests

diff --git a/test/libapt/run-tests b/test/libapt/run-tests
--- a/test/libapt/run-tests
+++ b/test/libapt/run-tests
@@ -53,6 +53,13 @@ do
 			"${tmppath}/ftp.de.debian.org_debian_dists_sid_main_i18n_Translation-pt" \
 			"${tmppath}/ftp.de.debian.org_debian_dists_sid_main_i18n_Translation-se~" \
 			"${tmppath}/ftp.de.debian.org_debian_dists_sid_main_i18n_Translation-st.bak"
+	elif [ $name = "HashSums${EXT}" ]; then
+		TMP="$(mktemp)"
+		dmesg > $TMP
+		echo -n "Testing with \033[1;35m${name}\033[0m ... "
+		LD_LIBRARY_PATH=${LDPATH} ${testapp} $TMP $(md5sum $TMP | cut -d' ' -f 1) $(sha1sum $TMP | cut -d' ' -f 1) $(sha256sum $TMP | cut -d' ' -f 1) $(sha512sum $TMP | cut -d' ' -f 1) && echo "\033[1;32mOKAY\033[0m" || echo "\033[1;31mFAILED\033[0m"
+		rm $TMP
+		continue
 	fi
 
 	echo -n "Testing with \033[1;35m${name}\033[0m ... "
