abicheck/run_abi_test: check for ../build; abicheck/apt_build.xml: fix version name

diff --git a/abicheck/run_abi_test b/abicheck/run_abi_test
--- a/abicheck/run_abi_test
+++ b/abicheck/run_abi_test
@@ -1,5 +1,10 @@
 #!/bin/sh
 
+if [ ! -d ../build ]; then
+	echo "../build missing, did you run make?"
+	exit 1
+fi
+
 LIBPATH=$(find /usr/lib/ -type f  -name "libapt-pkg*")
 sed s#@installed_libapt@#$LIBPATH# apt_installed.xml.in > apt_installed.xml
 
