test: Show statistics for parallel tests too
This makes things a bit nicer. We also include a list of passed
tests here, to use with --only to validate solver3 changes, as
well as the list of skipped tests.

But too lazy to implement these for the non-parallel case.

diff --git a/test/integration/run-tests b/test/integration/run-tests
--- a/test/integration/run-tests
+++ b/test/integration/run-tests
@@ -100,6 +100,9 @@ if [ -n "$TESTTORUN" ]; then
 	stty sane || true
 	cat >&2 "$OUTPUT"
 	stty sane || true
+	if [ "$STATS_FILE" ]; then
+		flock "$STATS_FILE" -c "echo $TESTTORUN skip=${SKIP:-no} fail=${FAIL:-no} >> \"$STATS_FILE\""
+	fi
 	if [ "$FAIL" = 'yes' ]; then
 		exit 1
 	else
@@ -119,6 +122,9 @@ else
 	TESTLIST="$(find . -mindepth 1 -maxdepth 1 -regex '^\./test-[^/]*$' | sort)"
 fi
 if [ -n "$APT_TEST_JOBS" ]; then
+	export STATS_FILE="$(mktemp)"
+	CURRENTTRAP="rm -f \"$STATS_FILE\"; $CURRENTTRAP"
+	trap "$CURRENTTRAP" 0 HUP INT QUIT ILL ABRT FPE SEGV PIPE TERM
 	if [ "$MSGCOLOR" != 'NO' ]; then
 		export MSGCOLOR='ALWAYS'
 	fi
@@ -128,7 +134,26 @@ if [ -n "$APT_TEST_JOBS" ]; then
 	elif command -v parallel.moreutils >/dev/null 2>&1; then
 		parallel=parallel.moreutils
 	fi
-	exec $parallel -j "$APT_TEST_JOBS" "./$(basename "$0")" -- $(echo "$TESTLIST")
+	$parallel -j "$APT_TEST_JOBS" "./$(basename "$0")" -- $(echo "$TESTLIST") || true
+	ALL=$(wc -l < "$STATS_FILE")
+	SKIP=$(grep -c "skip=yes" "$STATS_FILE" || true)
+	PASS=$(grep -c "skip=no fail=no" "$STATS_FILE" || true)
+	FAIL=$(grep -c "fail=yes" "$STATS_FILE" || true)
+	PASSED_TESTS=$(awk '! /fail=yes/ {print $1}' < "$STATS_FILE" | cut -f2 -d/ | sort | xargs)
+	SKIPPED_TESTS=$(awk '/fail=skip/ {print $1}' < "$STATS_FILE" | cut -f2 -d/ | sort | xargs)
+	FAILED_TESTS=$(awk '/fail=yes/ {print $1}' < "$STATS_FILE" | cut -f2 -d/ | sort | xargs)
+	echo >&2 "Statistics: $ALL tests were run: $PASS successfully and $FAIL failed, $SKIP skipped"
+	if [ -n "$FAILED_TESTS" ]; then
+		if [ $PASS -lt $FAIL ]; then
+			echo >&2 "Passed tests: $PASSED_TESTS"
+		else
+			echo >&2 "Failed tests: $FAILED_TESTS"
+		fi
+	else
+		echo >&2 'All tests seem to have been run successfully. What could possibly go wrong?'
+	fi
+	# ensure we don't overflow
+	exit $((FAIL <= 255 ? FAIL : 255))
 fi
 
 APT_TEST_SIGNINGHOME="$(mktemp --directory --tmpdir 'apt-key-signinghome.XXXXXXXXXX')"
